"""CAD-derived first-order screening; not hardware qualification."""
import json,math,csv
from pathlib import Path
import numpy as np
P=Path(__file__).resolve().parent
load=lambda n:json.loads((P/n).read_text(encoding='utf-8-sig'))
def save(n,x):(P/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
r=load('mass_properties.json');a=load('../cubli_reva/one_wheel_module/native_module_report.json');it=load('integration_native_report.json');v=it['variants'][1]
rows=r['parts'];wheelJ=r['wheel_Jz_kg_m2'];rotorJ=sum(x['centroid_tensor_terms_kg_m2'][2]+x['mass_kg']*((x['centroid_mm'][0]/1000)**2+(x['centroid_mm'][1]/1000)**2) for x in rows if x['group']=='rotor');J=rotorJ+6.9e-6
save('mass_comparison.json',{'status':'CONFIRMED_NATIVE_WITH_DENSITY_PROXIES','rev_a_module_kg':a['mass_kg'],'rev_b_module_kg':r['mass_kg'],'reduction_kg':a['mass_kg']-r['mass_kg'],'reduction_percent':100*(1-r['mass_kg']/a['mass_kg']),'bearing_mass_correction_kg':2*(.0279797-.019),'geometry_and_added_brake_change_kg':a['mass_kg']-r['mass_kg']-2*(.0279797-.019),'parts_rev_a_descending':sorted(a['parts'],key=lambda x:-x['mass_kg']),'parts_rev_b_descending':sorted(rows,key=lambda x:-x['mass_kg']),'wheel_inertia_gain_percent':100*(wheelJ/a['wheel_Jz_kg_m2']-1)})
# Conditional DC-equivalent energy model. Actual Micro electrical waveforms/conversion must be qualified.
Kt=.0377;Rcu=3*(.74/2)*.78**2;Ipeak_limit=3.5;Ieq_limit=Ipeak_limit/(.78*math.sqrt(2));Tcont=.112;Vbus=24;mod=.78;drag=.005;wcap=Vbus*mod/Kt
motor=[]
for rpm in [3000,4000,5000,6000]:
 w=rpm*2*math.pi/60;Tend=min(Tcont,Kt*Ieq_limit,max(0,(Vbus*mod-Kt*w)/Rcu*Kt));valid=Tend>drag
 x={'rpm':rpm,'conditional_reachable':valid,'catalogue_no_load_does_not_validate':True,'torque_at_target_Nm':Tend,'voltage_required_zero_load_equiv_V':Kt*w/mod,'energy_J':.5*J*w*w,'angular_momentum_Nms':rotorJ*w,'actual_current_rms_or_temperature_measured':False}
 if valid:
  t=0;loss=0;n=12000
  for i in range(n):
   wi=(i+.5)*w/n;T=min(Tcont,Kt*Ieq_limit,max(0,(Vbus*mod-Kt*wi)/Rcu*Kt));dt=J*(w/n)/(T-drag);t+=dt;loss+=(T/Kt)**2*Rcu*dt
  x.update(acceleration_time_s=t,mean_copper_loss_W=loss/t,DC_equiv_current_A=Tcont/Kt,phase_RMS_A=.78*Tcont/Kt,phase_peak_A=math.sqrt(2)*.78*Tcont/Kt,short_winding_increment_K=(loss/t)*3*(1-math.exp(-t/5)),continuous_ambient_to_winding_screen_K=(loss/t)*17.5)
 else:x['reason']='Conditional voltage/drag ceiling reached before target; no field-weakening claim'
 motor.append(x)
save('motor_analysis.json',{'classification':'CALCULATED_CONDITIONAL_SCREEN_NOT_VALIDATED_TORQUE_SPEED_CURVE','motor':'FAULHABER 4221 G 024 BXT H','driver':'ODrive Micro','bus_V':24,'modulation_assumption':mod,'warning':'DC-equivalent waveform model, current conversion AN190 and assumed Micro utilization. Manufacturer catalogue and Micro drive conventions are not a measured loaded curve. Do not set commissioning limits from this alone.','rotating_inertia_including_motor_kg_m2':J,'continuous_motor_torque_Nm':Tcont,'Micro_free_air_phase_peak_limit_assumption_A':Ipeak_limit,'conditional_no_load_ceiling_rpm':wcap*60/(2*math.pi),'results':motor,'thermal':'Housing heat sink and duty cycle unknown; 125C winding maximum is a limit, not a verified operating temperature.','alternative_screen':[{'driver':'ODrive S1','finding':'Higher current cannot remove a back-EMF voltage ceiling; larger/heavier. Loaded speed needs waveform and bus-voltage qualification.'},{'motor':'FAULHABER 4221 G 024 BXT H retained','finding':'Lower mass/lightweight motor comparison cannot be frozen without official torque-speed, flange and thermal data. No replacement geometry fabricated.'}]})
# Rectangle lies entirely inside annular disc, use its area-averaged radius.
rad=float(np.mean([math.hypot(x,y) for x in np.linspace(49.1,54.7,301) for y in np.linspace(-4,4,41)]))/1000
sens=[]
for mu in [.10,.15,.25,.35]:
 N=4/(2*mu*rad);F=N*.10/.70
 sens.append({'mu_assumed':mu,'each_pad_normal_N':N,'actuator_input_N':F,'PQ12_50N_lift_limit_pass':F<=50,'PQ12_40N_6mm_s_power_point_pass':F<=40,'closure_s_at_6mm_s':10/6,'friction_torque_both_directions_Nm':4})
stops=[{'rpm':n,'energy_J':.5*rotorJ*(n*2*math.pi/60)**2,'ideal_full_force_stop_s':rotorJ*(n*2*math.pi/60)/4,'brake_disc_adiabatic_bulk_delta_K':.5*rotorJ*(n*2*math.pi/60)**2/(next(x['mass_kg'] for x in rows if x['part']=='07_Brake_Drum')*500)} for n in [3000,4000,5000,6000]]
save('brake_analysis.json',{'status':'MECHANISM_CAD_COMPLETE_FOR_REVIEW_IMPULSE_BRAKE_HOLD','type':'Opposed pads, dual wedge slider, PQ12 slow proof actuator','effective_radius_m':rad,'pad_area_each_mm2':5.6*8,'input_mm':10,'lower_pad_mm':.65,'upper_pad_mm':.35,'total_closing_mm':1.0,'PQ12':{'MPN':'PQ12-100-12-P','stroke_mm':20,'mass_g':19,'max_lift_N':50,'peak_power_point_N':40,'peak_power_point_mm_s':6,'no_load_mm_s':10,'duty_percent':20,'backlash_mm':.25,'stall_current_A_12V':.210,'catalogue_stall_is_not_continuous_rating':True},'efficiency_assumption':.7,'sensitivity':sens,'stop_heat_screen':stops,'release':'Reverse actuator required; wedge friction, self-lock, backdrive and springs are unqualified. Power-loss release is NOT guaranteed.','friction_coefficient':'Assumed, not lining certification; wear/temperature/dust must be measured.','spring_collision_classification':'Four fixed-length spring solid envelopes overlap carriers at compressed states; intended envelope deformation, not verified actual spring clearance.'})
# Primary stress screen. No FEA performed; chosen material certificate remains HOLD.
N=4/(2*.15*rad);F=4/rad;L=.020;over=.0084;shock=3;diam=.010;M=F*over
sigma=32*M/(math.pi*diam**3);tau=16*4/(math.pi*diam**3);vm=math.sqrt(sigma*sigma+3*tau*tau)
span=.018;b=.028;t=.004;E=69e9
stress={'status':'CALCULATED_PRIMARY_SCREEN_NO_FEA','shaft':{'diameter_mm':10,'torque_Nm':4,'bending_Nm':M,'von_mises_MPa':vm/1e6,'shock_times_notch_screen_MPa':vm*shock*2/1e6,'required_certified_fatigue_allowable_MPa':vm*shock*2/1e6,'groove_mm':9.6,'groove_and_key_Kf_assumption':2,'positive_axial_retention':'DSH-10 external ring plus shoulder/shims; front bearing/retainer stack requires tolerance qualification'},'bearing':{'MPN':'SKF 6000-2Z','front_reaction_N':F*(1+over/L),'rear_reaction_N':F*over/L,'front_shock_N':shock*F*(1+over/L),'ideal_L10_million_rev_using_C4750':(4750/(shock*F*(1+over/L)))**3,'not_life_qualification':'Load impulse spectrum, fits, axial load and lubrication unresolved'},'caliper':{'cantilever_span_assumed_mm':18,'pad_N':N,'plate_t_mm':4,'normal_bending_MPa':6*N*span/(b*t*t)/1e6,'shock_bending_MPa':shock*6*N*span/(b*t*t)/1e6,'normal_deflection_mm':N*span**3/(3*E*(b*t**3/12))*1000,'6061_T6_min_yield_assumption_MPa':240,'fastener_M3':{'two_screw_direct_shear_each_N':shock*F/2,'joint_prying_thread_engagement_HOLD':True}},'rim':{'material':'steel density proxy, grade HOLD','at6000_thin_ring_hoop_MPa':7800*(6000*2*math.pi/60*.075)**2/1e6,'overspeed_factor':1.25,'at7500_hoop_MPa':7800*(7500*2*math.pi/60*.075)**2/1e6,'qualification':'Rim seams/holes/spoke joints, balance, fatigue and containment are NOT covered by thin-ring screen'},'torsional_coupling':{'parts':['Ruland MJC25-6-A','Ruland MJC25-10-A','JD16/25-92Y','own 5-to-6 split sleeve'],'drawing_status':'Manufacturer outer envelope and hub sizes; jaw/insert internals not modeled','mass_kg_assumption':.032,'speed_catalogue_limit_rpm':8000,'sleeve_runout_and_clamp_torque_HOLD':True,'braking_torque_path':'Wheel to disc to caliper to frame; motor coupling carries rotor/deceleration inertia, not designed as primary 4Nm reaction path'}}
save('strength_analysis.json',stress)
# Face/edge angular-impulse screening, not a hybrid contact dynamics simulation.
m=v['mass_kg']+.150;c=np.array(v['COM_mm'])/1000;side=.280;half=side/2;terms=v['centroid_tensor_terms_kg_m2'];I=np.array([[terms[0],-terms[3],-terms[5]],[-terms[3],terms[1],-terms[4]],[-terms[5],-terms[4],terms[2]]]);distance=np.array([c[0]-half,0,c[2]+half]);dh=np.linalg.norm(distance)-(c[2]+half);Iedge=I[1,1]+m*np.dot(distance,distance);Ebar=m*9.80665*dh;H=math.sqrt(2*Iedge*Ebar);q=np.array([1.,-1.,0])/math.sqrt(2);dc=c-np.array([half,half,-half]);Ip=float(q@I@q+m*(dc@dc-(dc@q)**2));edgeheight=math.hypot(half-c[0],half+c[2]);cornerheight=np.linalg.norm(dc);dhe=max(0,cornerheight-edgeheight);Hp=math.sqrt(2*Ip*m*9.80665*dhe)
getup=[]
for eta in [.9,.7,.5]:
 getup.append({'impulse_transfer_fraction_assumption':eta,'face_to_edge_required_H_Nms':H/eta,'face_to_edge_wheel_rpm':H/eta/rotorJ*60/(2*math.pi),'edge_to_point_required_H_Nms':Hp/eta,'edge_to_point_equal_two_wheel_rpm':Hp/eta/(math.sqrt(2)*rotorJ)*60/(2*math.pi)})
save('three_axis_feasibility.json',{'status':'GET_UP_NOT_VALIDATED_MANUFACTURING_HOLD','native_module_kg':r['mass_kg'],'native_shared_assembly_kg':v['mass_kg'],'missing_hardware_harness_mounting_reserve_kg_assumption':.150,'completed_mass_estimate_kg':m,'standalone_kg':it['variants'][0]['mass_kg'],'shared_frame_improvement_kg':it['variants'][0]['mass_kg']-v['mass_kg'],'COM_mm':v['COM_mm'],'centroid_native_inertia_terms_kg_m2':terms,'terms_order':'Ixx Iyy Izz Ixy Iyz Ixz; cross terms treated as products for matrix; confirm sign for downstream solver','allocation_matrix':[[1,0,0],[0,1,0],[0,0,1]],'rank':3,'condition_number':1,'axis_offset_is_not_collocated':True,'frame_size_mm':280,'face_to_edge_barrier_J':Ebar,'face_to_edge_locked_axis_inertia_kg_m2':Iedge,'edge_to_point_potential_screen_delta_m':dhe,'impulse_sensitivity':getup,'micro_conditional_angular_momentum_Nms':rotorJ*wcap,'contact_friction_sensitivity_mu':[.3,.5,.8],'contact_simulation':'NOT RUN; edge changes, sliding, compliance and impacts are not solved. Impulse-transfer fractions bound losses only, not success probability.','conclusion':'CAD packing is feasible at static reviewed poses; self-righting is not established and current slow actuator is unsuitable for abrupt launch braking.'})
with (P/'BOM.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.writer(f,lineterminator="\n");w.writerow(['Part ID','Part name','Quantity','Material','Mass kg','Manufacturing method','Manufacturer/MPN','Notes'])
 for x in rows:
  purchased='';method='fabricated prototype HOLD';note='Material proxy; final tolerances and fasteners HOLD'
  if x['part'].startswith('14'):purchased='SKF 6000-2Z';method='purchased';note='Catalogue19g mass override'
  if x['part'].startswith('15'):purchased='FAULHABER 4221 G 024 BXT H';method='purchased';note='140g stator envelope plus separately modeled rotor shaft;142g nominal total'
  if x['part'].startswith('31'):purchased='Actuonix PQ12-100-12-P';method='purchased envelope';note='P+rod aggregate19g; mount coordinates provisional; slow proof only'
  if x['part'].startswith('21'):purchased='Rotor Clip DSH-10';method='purchased envelope';note='Groove9.54..9.60x1.1; installed lugs simplified'
  w.writerow([x['part'],x['part'],1,x['material'],x['mass_kg'],method,purchased,note])
 for name,qty,mpn,note in [('Coupling hub motor',1,'Ruland MJC25-6-A','within coupling aggregate mass assumption'),('Coupling hub wheel',1,'Ruland MJC25-10-A','within coupling aggregate mass assumption'),('Coupling spider',1,'JD16/25-92Y','torque/misalignment rating HOLD'),('Return springs',4,'TBD','wire geometry/rate/solid height not frozen'),('Fasteners and wiring',1,'TBD','Included only in150g system reserve; exact lengths/quantities HOLD')]:w.writerow([name,name,qty,'TBD','included aggregate/TBD','purchased',mpn,note])
print('Calculated CAD-based screens',r['mass_kg'],wheelJ,getup)
